# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - astrixApi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

#      - name: dotnet publish
#        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: dotnet publish API
        run: dotnet publish ${{github.workspace}}/LMS.API/LMS.API.csproj -c Release -o "${{github.workspace}}/publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/publish
#         path: ${{env.DOTNET_ROOT}}/myapp

      - name: Install EntityFrameworkCore Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
 
      - name: Generate EF Core Migration Script
        run: dotnet ef migrations script --idempotent --configuration Release --no-build --output "${{github.workspace}}/sql/sql-script.sql" --context LMS.Infractructure.Data.ApplicationDbContext --project ${{github.workspace}}/LMS.API/LMS.API.csproj
 
      - uses: actions/upload-artifact@v4
        with:

          name: ddl-updates
          path: ${{github.workspace}}/sql/sql-script.sql

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Download SQL artifact

        uses: actions/download-artifact@v4
        with:

          name: ddl-updates
          path: ./ddl-updates


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C6718C1463414F4193C0BF3A7E0081EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C0AF604C0DBF4CEDB850F2DF25708099 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_88BEB4F5937B4739843FE7BC73B373B8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'astrixApi'
          slot-name: 'Production'
          package: ./publish

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2

        with:
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          path: ./ddl-updates/sql-script.sql
          

